# Generated by Django 3.1.7 on 2021-02-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='task_status',
            field=models.CharField(default='', max_length=60),
        ),
    ]
